name: CI for QuickPizza

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Install k6
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg software-properties-common
        curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt-get update
        sudo apt-get install -y k6

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install working CLI version of k6-html-reporter
      run: npm install -g @danielschmid/k6-html-reporter

    - name: Run k6 tests and generate JSON
      run: k6 run --out json=report.json test-script.js

    - name: Generate HTML report
      run: k6-html-reporter --json report.json --output report.html

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: k6-html-report
        path: report.html
